export let CustomerOrder = [
  {
    tableNo: 25,
    customer: "Dhiraj Temkar",
    dishSelected: [
      {
        id: 0,
        name: "Mutton Biryani",
        count: 2,
        total: 80,
        isCustomized: true,
        customOptions: {
          size: "ExtraLarge",
          select: ["cheeseBurst", "Spicy", "Jyada Lao"],
        },
        rating: 4,
        price: 40,
        checkHai: true,
      },
      {
        id: 1,
        name: "McAloBurger",
        count: 3,
        total: 60,
        isCustomized: false,
        customOptions: {},
        rating: 3,
        price: 20,
        checkHai: true,
      },
      {
        id: 2,
        name: "Chicken Fry",
        count: 1,
        total: 50,
        isCustomized: false,
        customOptions: {},
        rating: 4,
        price: 50,
        checkHai: true,
      },
      {
        id: 3,
        name: "Limbu Sharbat",
        count: 2,
        total: 20,
        isCustomized: true,
        customOptions: {
          size: "Medium",
          select: ["ExtraCold", "straw dena"],
        },
        rating: 5,
        price: 10,
        checkHai: true,
      },
    ],
    id: "0",
    total: 210,
    code: "#213074",
    date: "09-08-2020",
    hotelName: "Brinda's Cafe",
    // time: comp.time,
    // image: comp.hotelImage,
    locality: "Santacruz East, Mumbai",
    Status: "New",
    orderBuild: true, // update if order cancle
    orderState: "prep",
  },
  {
    tableNo: 25,
    customer: "Dhiraj Temkar",
    dishSelected: [
      {
        id: 0,
        name: "Mutton Biryani",
        count: 2,
        total: 80,
        isCustomized: true,
        customOptions: {
          size: "ExtraLarge",
          select: ["cheeseBurst", "Spicy", "Jyada Lao"],
        },
        rating: 4,
        price: 40,
        checkHai: true,
      },
      {
        id: 1,
        name: "McAloBurger",
        count: 3,
        total: 60,
        isCustomized: false,
        customOptions: {},
        rating: 3,
        price: 20,
        checkHai: true,
      },
      {
        id: 2,
        name: "Chicken Fry",
        count: 1,
        total: 50,
        isCustomized: false,
        customOptions: {},
        rating: 4,
        price: 50,
        checkHai: true,
      },
      {
        id: 3,
        name: "Limbu Sharbat",
        count: 2,
        total: 20,
        isCustomized: true,
        customOptions: {
          size: "Medium",
          select: ["ExtraCold", "straw dena"],
        },
        rating: 5,
        price: 10,
        checkHai: true,
      },
    ],
    id: "1",
    total: 210,
    code: "#213074",
    date: "09-08-2020",
    hotelName: "Brinda's Cafe",
    // time: comp.time,
    // image: comp.hotelImage,
    locality: "Santacruz East, Mumbai",
    Status: "New",
    orderBuild: true, // update if order cancle
    orderState: "Generate",
    abc: [
      {
        personName: "Dhiraj",
        id: 1,
        OrderDetails: [
          {
            count: 1,
            name: "ice-cream",
            total: 12,
            checked: true,
            disable: false,
          },
          {
            count: 2,
            name: "Chicken Crispy",
            total: 35,
            checked: true,
            disable: false,
          },
        ],
      },
      {
        personName: "Brinda",
        id: 1,
        OrderDetails: [
          {
            count: 1,
            name: "Chicken Crispy",
            total: 17.5,
            checked: true,
            disable: false,
          },
        ],
      },
      {
        personName: "Sheetal",
        id: 1,
        OrderDetails: [
          {
            count: 1,
            name: "ice-cream",
            total: 12,
            checked: true,
            disable: false,
          },
          {
            count: 1,
            name: "Chicken Crispy",
            total: 17.5,
            checked: true,
            disable: false,
          },
        ],
      },
    ],
    totalAmount: 250,
  },
  {
    tableNo: 7,
    customer: "Dhiraj Temkar",
    dishSelected: [
      {
        id: 0,
        name: "Mutton Biryani",
        count: 2,
        total: 80,
        isCustomized: true,
        customOptions: {
          size: "ExtraLarge",
          select: ["cheeseBurst", "Spicy", "Jyada Lao"],
        },
        rating: 4,
        price: 40,
        checkHai: true,
      },
      {
        id: 1,
        name: "Mc Aloo Burger",
        count: 3,
        total: 60,
        isCustomized: false,
        customOptions: {},
        rating: 3,
        price: 20,
        checkHai: true,
      },
      {
        id: 2,
        name: "Chicken Fry",
        count: 1,
        total: 50,
        isCustomized: false,
        customOptions: {},
        rating: 4,
        price: 50,
        checkHai: true,
      },
      {
        id: 3,
        name: "Limbu Sharbat",
        count: 2,
        total: 20,
        isCustomized: true,
        customOptions: {
          size: "Medium",
          select: ["ExtraCold", "straw dena"],
        },
        rating: 5,
        price: 10,
        checkHai: true,
      },
      {
        id: 4,
        name: "Roti",
        count: 1,
        total: 50,
        isCustomized: false,
        customOptions: {},
        rating: 4,
        price: 50,
        checkHai: true,
      },
      {
        id: 5,
        name: "Chicken Tikka",
        count: 1,
        total: 50,
        isCustomized: false,
        customOptions: {},
        rating: 4,
        price: 50,
        checkHai: true,
      },
      {
        id: 2,
        name: "Chicken Malai",
        count: 1,
        total: 50,
        isCustomized: false,
        customOptions: {},
        rating: 4,
        price: 50,
        checkHai: true,
      },
    ],
    id: "2",
    total: 210,
    code: "#213074",
    date: "09-08-2020",
    hotelName: "Brinda's Cafe",
    // time: comp.time,
    // image: comp.hotelImage,
    locality: "Santacruz East, Mumbai",
    Status: "New",
    orderBuild: true, // update if order cancle
    orderState: "prep",
  },
  {
    tableNo: 25,
    customer: "Dhiraj Temkar",
    dishSelected: [
      {
        id: 0,
        name: "Mutton Biryani",
        count: 2,
        total: 80,
        isCustomized: true,
        customOptions: {
          size: "ExtraLarge",
          select: ["cheeseBurst", "Spicy", "Jyada Lao"],
        },
        rating: 4,
        price: 40,
        checkHai: true,
      },
      {
        id: 1,
        name: "McAloBurger",
        count: 3,
        total: 60,
        isCustomized: false,
        customOptions: {},
        rating: 3,
        price: 20,
        checkHai: true,
      },
      {
        id: 2,
        name: "Chicken Fry",
        count: 1,
        total: 50,
        isCustomized: false,
        customOptions: {},
        rating: 4,
        price: 50,
        checkHai: true,
      },
      {
        id: 3,
        name: "Limbu Sharbat",
        count: 2,
        total: 20,
        isCustomized: true,
        customOptions: {
          size: "Medium",
          select: ["ExtraCold", "straw dena"],
        },
        rating: 5,
        price: 10,
        checkHai: true,
      },
    ],
    id: "3",
    total: 210,
    code: "#213074",
    date: "09-08-2020",
    hotelName: "Brinda's Cafe",
    // time: comp.time,
    // image: comp.hotelImage,
    locality: "Santacruz East, Mumbai",
    Status: "New",
    orderBuild: true, // update if order cancle
    orderState: "new",
  },
  {
    tableNo: 25,
    customer: "Dhiraj Temkar",
    dishSelected: [
      {
        id: 0,
        name: "Mutton Biryani",
        count: 2,
        total: 80,
        isCustomized: true,
        customOptions: {
          size: "ExtraLarge",
          select: ["cheeseBurst", "Spicy", "Jyada Lao"],
        },
        rating: 4,
        price: 40,
        checkHai: true,
      },
      {
        id: 1,
        name: "McAloBurger",
        count: 3,
        total: 60,
        isCustomized: false,
        customOptions: {},
        rating: 3,
        price: 20,
        checkHai: true,
      },
      {
        id: 2,
        name: "Chicken Fry",
        count: 1,
        total: 50,
        isCustomized: false,
        customOptions: {},
        rating: 4,
        price: 50,
        checkHai: true,
      },
      {
        id: 3,
        name: "Limbu Sharbat",
        count: 2,
        total: 20,
        isCustomized: true,
        customOptions: {
          size: "Medium",
          select: ["ExtraCold", "straw dena"],
        },
        rating: 5,
        price: 10,
        checkHai: true,
      },
    ],
    id: "4",
    total: 210,
    code: "#213074",
    date: "09-08-2020",
    hotelName: "Brinda's Cafe",
    // time: comp.time,
    // image: comp.hotelImage,
    locality: "Santacruz East, Mumbai",
    Status: "New",
    orderBuild: true, // update if order cancle
    orderState: "ready",
  },
  {
    tableNo: 25,
    customer: "Dhiraj Temkar",
    dishSelected: [
      {
        id: 0,
        name: "Mutton Biryani",
        count: 2,
        total: 80,
        isCustomized: true,
        customOptions: {
          size: "ExtraLarge",
          select: ["cheeseBurst", "Spicy", "Jyada Lao"],
        },
        rating: 4,
        price: 40,
        checkHai: true,
      },
      {
        id: 1,
        name: "McAloBurger",
        count: 3,
        total: 60,
        isCustomized: false,
        customOptions: {},
        rating: 3,
        price: 20,
        checkHai: true,
      },
      {
        id: 2,
        name: "Chicken Fry",
        count: 1,
        total: 50,
        isCustomized: false,
        customOptions: {},
        rating: 4,
        price: 50,
        checkHai: true,
      },
      {
        id: 3,
        name: "Limbu Sharbat",
        count: 2,
        total: 20,
        isCustomized: true,
        customOptions: {
          size: "Medium",
          select: ["ExtraCold", "straw dena"],
        },
        rating: 5,
        price: 10,
        checkHai: true,
      },
    ],
    id: "5",
    total: 210,
    code: "#213074",
    date: "09-08-2020",
    hotelName: "Brinda's Cafe",
    // time: comp.time,
    // image: comp.hotelImage,
    locality: "Santacruz East, Mumbai",
    Status: "New",
    orderBuild: true, // update if order cancle
    orderState: "ready",
  },
  {
    tableNo: 25,
    customer: "Dhiraj Temkar",
    dishSelected: [
      {
        id: 0,
        name: "Mutton Biryani",
        count: 2,
        total: 80,
        isCustomized: true,
        customOptions: {
          size: "ExtraLarge",
          select: ["cheeseBurst", "Spicy", "Jyada Lao"],
        },
        rating: 4,
        price: 40,
        checkHai: true,
      },
      {
        id: 1,
        name: "McAloBurger",
        count: 3,
        total: 60,
        isCustomized: false,
        customOptions: {},
        rating: 3,
        price: 20,
        checkHai: true,
      },
      {
        id: 2,
        name: "Chicken Fry",
        count: 1,
        total: 50,
        isCustomized: false,
        customOptions: {},
        rating: 4,
        price: 50,
        checkHai: true,
      },
      {
        id: 3,
        name: "Limbu Sharbat",
        count: 2,
        total: 20,
        isCustomized: true,
        customOptions: {
          size: "Medium",
          select: ["ExtraCold", "straw dena"],
        },
        rating: 5,
        price: 10,
        checkHai: true,
      },
    ],
    id: "6",
    total: 210,
    code: "#777777",
    date: "09-08-2020",
    hotelName: "Brinda's Cafe",
    // time: comp.time,
    // image: comp.hotelImage,
    locality: "Santacruz East, Mumbai",
    Status: "New",
    orderBuild: true, // update if order cancle
    orderState: "Generate",
    abc: [
      {
        personName: "Dhiraj",
        id: 1,
        OrderDetails: [
          {
            count: 1,
            name: "ice-cream",
            total: 12,
            checked: true,
            disable: false,
          },
          {
            count: 2,
            name: "Chicken Crispy",
            total: 35,
            checked: true,
            disable: false,
          },
        ],
      },
      {
        personName: "Brinda",
        id: 1,
        OrderDetails: [
          {
            count: 1,
            name: "Chicken Crispy",
            total: 17.5,
            checked: true,
            disable: false,
          },
        ],
      },
      {
        personName: "Sheetal",
        id: 1,
        OrderDetails: [
          {
            count: 1,
            name: "ice-cream",
            total: 12,
            checked: true,
            disable: false,
          },
          {
            count: 1,
            name: "Chicken Crispy",
            total: 17.5,
            checked: true,
            disable: false,
          },
        ],
      },
    ],
    totalAmount: 250,
  },
  {
    tableNo: 25,
    customer: "Dhiraj Temkar",
    dishSelected: [
      {
        id: 0,
        name: "Mutton Biryani",
        count: 2,
        total: 80,
        isCustomized: true,
        customOptions: {
          size: "ExtraLarge",
          select: ["cheeseBurst", "Spicy", "Jyada Lao"],
        },
        rating: 4,
        price: 40,
        checkHai: true,
      },
      {
        id: 1,
        name: "McAloBurger",
        count: 3,
        total: 60,
        isCustomized: false,
        customOptions: {},
        rating: 3,
        price: 20,
        checkHai: true,
      },
      {
        id: 2,
        name: "Chicken Fry",
        count: 1,
        total: 50,
        isCustomized: false,
        customOptions: {},
        rating: 4,
        price: 50,
        checkHai: true,
      },
      {
        id: 3,
        name: "Limbu Sharbat",
        count: 2,
        total: 20,
        isCustomized: true,
        customOptions: {
          size: "Medium",
          select: ["ExtraCold", "straw dena"],
        },
        rating: 5,
        price: 10,
        checkHai: true,
      },
    ],
    id: "7",
    total: 210,
    code: "#213074",
    date: "09-08-2020",
    hotelName: "Brinda's Cafe",
    // time: comp.time,
    // image: comp.hotelImage,
    locality: "Santacruz East, Mumbai",
    Status: "New",
    orderBuild: true, // update if order cancle
    orderState: "new",
  },
];
